### ISSUE TITLE
Did you notice any performance gain after switching from python to c++?

### ISSUE THREAD

**Issue by ricardodeazambuja** [AscendNTNU/msp_flightcontroller_interface#1]
Hi,

I noticed you switched from python to c++ so I would like to know if there was any performance improvement from that. My python library communicates at around 100Hz running on a RPI Zero, but if c++ makes it much faster that would be quite useful for the RPI Zero because it's single core.

Cheers,
Ricardo

**Comment by birktj** [comment]
I switched to c++ mostly because I am more comfortable with c++ and I prefer static typing. I thought I could write it quickly in python, but then I got a lot of bugs that I am used to catch with the typechecker and I didn't really know how to deal with it :joy:. So it is mostly a question of personal preference. I think performance is more limited by serial baudrate than anything else.

**Comment by ricardodeazambuja** [comment]
Thanks!
